version: '3'
services:
  cli:
    image: nats-cli
    build:
      context: .
    env_file:
      - local.env
    networks:
      - nats-network
    volumes:
      - ./:/app/

networks:
  nats-network:
